Repository DEFRA/sroc-acceptance-tests, pull requests merged in 2022-04, with the labels that each got.

#68 Add feature for enabled and disabled users
  cypress/integration/authorisation/disabled_enabled.feature
  cypress/integration/authorisation/disabled_enabled/disabled_enabled_steps.js
Labels: enhancement

#75 Add bugs feature
  cypress/integration/bugs/general.feature
  cypress/integration/bugs/general/general_steps.js
  cypress/integration/common/general.js
  cypress/support/commands.js
  cypress/support/helpers.js
Labels: enhancement

#76 Move legacy sort checks to their own feature
  cypress/fixtures/pasai394.dat.csv
  cypress/fixtures/wmlai394.DAT.csv
  cypress/integration/legacy/cfd.feature
  cypress/integration/legacy/cfd/cfd_steps.js
  cypress/integration/legacy/pas.feature
  cypress/integration/legacy/pas/pas_steps.js
  cypress/integration/legacy/wml.feature
  cypress/integration/legacy/wml/wml_steps.js
  cypress/integration/transactions/sorting.feature
  cypress/integration/transactions/sorting/sorting_steps.js
  cypress/support/helpers.js
Labels: enhancement

#77 Delete legacy Download data checks
  cypress/integration/data_export/general.feature
  cypress/integration/legacy/cfd.feature
  cypress/integration/legacy/cfd/cfd_steps.js
  cypress/integration/legacy/pas.feature
  cypress/integration/legacy/pas/pas_steps.js
  cypress/integration/legacy/wml.feature
  cypress/integration/legacy/wml/wml_steps.js
Labels: housekeeping

#79 Add our first table object
  cypress/integration/bugs/general/general_steps.js
  cypress/integration/legacy/cfd/cfd_steps.js
  cypress/integration/legacy/pas/pas_steps.js
  cypress/integration/legacy/wml/wml_steps.js
  cypress/integration/transactions/general.feature
  cypress/integration/transactions/general/general_steps.js
  cypress/integration/transactions/sorting/sorting_steps.js
  cypress/pages/tables/base_table.js
  cypress/pages/tables/transactions_to_be_billed_table.js
  cypress/pages/transactions_page.js
  cypress/support/helpers.js
Labels: housekeeping

#78 Move exclude transaction to own feature
  cypress/integration/exclusions/general.feature
  cypress/integration/exclusions/general/general_steps.js
  cypress/integration/legacy/cfd.feature
  cypress/integration/legacy/cfd/cfd_steps.js
  cypress/integration/legacy/pas.feature
  cypress/integration/legacy/pas/pas_steps.js
  cypress/integration/legacy/wml.feature
  cypress/integration/legacy/wml/wml_steps.js
  cypress/pages/transaction_detail_page.js
Labels: enhancement

#80 Move legacy transaction history check to feature
  cypress/integration/legacy/cfd.feature
  cypress/integration/legacy/cfd/cfd_steps.js
  cypress/integration/legacy/pas.feature
  cypress/integration/legacy/pas/pas_steps.js
  cypress/integration/legacy/wml.feature
  cypress/integration/legacy/wml/wml_steps.js
  cypress/integration/transactions/history.feature
  cypress/integration/transactions/history/history_steps.js
  cypress/pages/tables/transaction_change_history_table.js
  cypress/pages/transaction_change_history_page.js
Labels: housekeeping

#82 Move legacy page export steps to new feature
  cypress/integration/data_export/export_entries.feature
  cypress/integration/data_export/export_entries/export_entries_steps.js
  cypress/integration/legacy/cfd.feature
  cypress/integration/legacy/cfd/cfd_steps.js
  cypress/integration/legacy/pas.feature
  cypress/integration/legacy/pas/pas_steps.js
  cypress/integration/legacy/wml.feature
  cypress/integration/legacy/wml/wml_steps.js
Labels: housekeeping

#83 Move legacy transaction detail steps to new feature
  cypress/fixtures/wmlai394.DAT.csv
  cypress/integration/legacy/cfd.feature
  cypress/integration/legacy/cfd/cfd_steps.js
  cypress/integration/legacy/pas.feature
  cypress/integration/legacy/pas/pas_steps.js
  cypress/integration/legacy/wml.feature
  cypress/integration/legacy/wml/wml_steps.js
  cypress/integration/transactions/general.feature
  cypress/integration/transactions/general/general_steps.js
Labels: housekeeping

#85 Add validation test
  cypress/integration/validation/general.feature
  cypress/integration/validation/general/general_steps.js
  cypress/pages/add_permit_category_page.js
  cypress/pages/permit_categories_page.js
Labels: bug

#89 Move legacy page checking steps to new feature
  cypress/integration/email/expired_tokens/expired_tokens_steps.js
  cypress/integration/email/general/general_steps.js
  cypress/integration/legacy/cfd.feature
  cypress/integration/legacy/cfd/cfd_steps.js
  cypress/integration/legacy/pas.feature
  cypress/integration/legacy/pas/pas_steps.js
  cypress/integration/legacy/wml.feature
  cypress/integration/legacy/wml/wml_steps.js
  cypress/integration/smoke/general.feature
  cypress/integration/smoke/general/general_steps.js
  cypress/pages/add_permit_category_page.js
  cypress/pages/annual_billing_file_details_page.js
  cypress/pages/annual_billing_page.js
  cypress/pages/change_password_page.js
  cypress/pages/excluded_transactions_page.js
  cypress/pages/exclusion_reasons_page.js
  cypress/pages/export_data_page.js
  cypress/pages/forgot_password_confirm_page.js
  cypress/pages/imported_transaction_files_page.js
  cypress/pages/menus/main_menu.js
  cypress/pages/permit_categories_page.js
  cypress/pages/retrospective_transactions_page.js
  cypress/pages/transaction_file_history_page.js
  cypress/pages/transaction_history_page.js
Labels: housekeeping

#93 Add to legacy features auto checking of exports
  cypress/integration/common/legacy.js
  cypress/integration/common/read_export.js
  cypress/integration/legacy/cfd.feature
  cypress/integration/legacy/pas.feature
  cypress/integration/legacy/wml.feature
  cypress/integration/transactions/export.feature
  cypress/support/commands.js
  cypress/support/helpers.js
Labels: enhancement
